text[0] = "According to all known laws of aviation, a bee should not"
text[1] = "Be able to fly, its wings are too small to get their fat"
text[2] = "Bodies off the ground, and yet, the bee flies anyway"
text[3] = "The bee does not care what humans think is impossible"
text[4] = "fuck shit cum ass penis barf cock bitch cunt prick"
text[5] = "get out of my room i am playing the minecraft motherfucker"
text[6] = "somebody once told me the world was gonna roll me, i aint the"