text[0] = "My mother always said the great green orb is why I can"
text[1] = "tell how cold it is in here... I'd much rather not be able"
text[2] = "to tell at all, frankly."
text[3] = ""
text[4] = ""